using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using wServer.logic.behaviors;
using wServer.logic.transitions;
using wServer.logic.loot;

namespace wServer.logic
{
    partial class BehaviorDb
    {
        private const float fixedAngle_RingAttack2 = 22.5f;

        private _ Belladonna = () => Behav()
            .Init("vlntns Botany Bella",
                new State(
                    new TransformOnDeath("vlntns Loot Balloon Bella", returnToSpawn: true),
                    new CopyDamageOnDeath("vlntns Loot Balloon Bella"),
                    //new Taunt(new string[3]
                    //{
                    //    "Start",
                    //    "Ring_Attack",
                    //    "Ring_Attack2"
                    //},
                    //text: "You are nothing more than nutiment for my roots.", cooldown: 15000),

                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new PlayerWithinTransition(10, "Start")
                    ),
                    new State("Start",
                        new Taunt("You are nothing more than nutiment for my roots."),
                        new Shoot(10, count: 4, shootAngle: (float)(180 / 4), predictive: 0.7, coolDown: 1000),
                        new Shoot(10, count: 2, shootAngle: (float)30, angleOffset: (float)45, projectileIndex: 3, coolDown: 1000),
                        new Shoot(10, count: 2, shootAngle: (float)30, angleOffset: (float)-45, projectileIndex: 3, coolDown: 1000),
                        new HpLessTransition(0.9, "Ring_Attack")
                    ),
                    new State("Ring_Attack",
                        new Prioritize(
                            new StayCloseToSpawn(0.5, 10),
                            new Wander(0.5)
                        ),
                        new Shoot(10, count: 12, projectileIndex: 1, coolDown: 5000),
                        new Shoot(10, count: 12, projectileIndex: 1, coolDown: 3000),
                        new HpLessTransition(0.7, "Ring_Attack2")
                    ),
                    new State("Ring_Attack2",
                        new State("Yo_man_I_show_you_what_I_can_do",
                            new Timed(600, new Shoot(10, count: 12)),
                            new TimedTransition(800, "Ring")
                        ),
                        new State("Ring",
                            new Shoot(0, count: 6, projectileIndex: 2, fixedAngle: 0),
                            new TimedTransition(250, "Ring1")
                        ),
                        new State("Ring1",
                            new Shoot(0, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2),
                            new TimedTransition(250, "Ring2")
                        ),
                        new State("Ring2",
                            new Shoot(0, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 2),
                            new TimedTransition(250, "Ring3")
                        ),
                        new State("Ring3",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 3),
                            new TimedTransition(250, "Ring4")
                        ),
                        new State("Ring4",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 4),
                            new TimedTransition(250, "Ring5")
                        ),
                        new State("Ring5",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 5),
                            new TimedTransition(250, "-Ring")
                        ),
                        new State("-Ring",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 6),
                            new TimedTransition(250, "-Ring1")
                        ),
                        new State("-Ring1",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 5),
                            new TimedTransition(250, "-Ring2")
                        ),
                        new State("-Ring2",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 4),
                            new TimedTransition(250, "-Ring3")
                        ),
                        new State("-Ring3",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 3),
                            new TimedTransition(250, "-Ring4")
                        ),
                        new State("-Ring4",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2 * 2),
                            new TimedTransition(250, "-Ring5")
                        ),
                        new State("-Ring5",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: fixedAngle_RingAttack2),
                            new TimedTransition(250, "-Ring6")
                        ),
                        new State("-Ring6",
                            new Shoot(10, count: 6, projectileIndex: 2, fixedAngle: 0),
                            new Timed(200, new Shoot(10, count: 2, shootAngle: (float)30, defaultAngle: (float)45, projectileIndex: 3)),
                            new Timed(200, new Shoot(10, count: 2, shootAngle: (float)30, defaultAngle: (float)135, projectileIndex: 3)),
                            new TimedTransition(200, "StartTheFun")
                        )
                    ),
                    new State("StartTheFun",
                        new Taunt(true, 0, "You will be as food for my children!"),
                        new Flash(0xf0e68c, flashPeriod: 0.5, flashRepeats: 10),
                        new ReturnToSpawn(speed: 1),
                        new TimedTransition(5000, "RAGE_MODE")
                    ),
                    new State("RAGE_MODE",
                        new State("Everything_is_cool",
                            new State("spawn_minions",
                                new HpLessTransition(0.22, "OMG_HALP_ME_BUDS!!!!!!!!!!!!!!1111111oneoneoneeleven"),
                                new InvisiToss("vlntns Red", range: 9.9, angle: 15),
                                new InvisiToss("vlntns White", range: 6.6, angle: 30),
                                new InvisiToss("vlntns Yellow", range: 3.3, angle: 45),
                                new InvisiToss("vlntns White", range: 9.9, angle: 60),
                                new InvisiToss("vlntns Red", range: 6.6, angle: 75),
                                new InvisiToss("vlntns White", range: 3.3, angle: 90),
                                new InvisiToss("vlntns Yellow", range: 9.9, angle: 105),
                                new InvisiToss("vlntns White", range: 6.6, angle: 120),

                                new InvisiToss("vlntns Red", range: 3.3, angle: 135),
                                new InvisiToss("vlntns White", range: 9.9, angle: 150),
                                new InvisiToss("vlntns Yellow", range: 6.6, angle: 165),
                                new InvisiToss("vlntns White", range: 3.3, angle: 180),
                                new InvisiToss("vlntns Red", range: 9.9, angle: 195),
                                new InvisiToss("vlntns White", range: 6.6, angle: 210),
                                new InvisiToss("vlntns Yellow", range: 3.3, angle: 225),
                                new InvisiToss("vlntns White", range: 9.9, angle: 240),

                                new InvisiToss("vlntns Red", range: 6.6, angle: 255),
                                new InvisiToss("vlntns White", range: 3.3, angle: 270),
                                new InvisiToss("vlntns Yellow", range: 9.9, angle: 285),
                                new InvisiToss("vlntns White", range: 6.6, angle: 300),
                                new InvisiToss("vlntns Red", range: 3.3, angle: 315),
                                new InvisiToss("vlntns White", range: 9.9, angle: 330),
                                new InvisiToss("vlntns Yellow", range: 6.6, angle: 345),
                                new InvisiToss("vlntns White", range: 3.3, angle: 360),

                                new Spawn("vlntns Bella Buds", maxChildren: 5, initialSpawn: 1),
                                new TimedTransition(0, "shoot1")
                            ),
                            new State("shoot1",
                                new HpLessTransition(0.2, "OMG_HALP_ME_BUDS!!!!!!!!!!!!!!1111111oneoneoneeleven"),
                                new Shoot(0, projectileIndex: 1, fixedAngle: 45),
                                new Shoot(0, projectileIndex: 1, fixedAngle: 135),
                                new Shoot(0, projectileIndex: 1, fixedAngle: 225),
                                new Shoot(0, projectileIndex: 1, fixedAngle: 315),
                                new TimedTransition(800, "shoot2")
                            ),
                            new State("shoot2",
                                new HpLessTransition(0.2, "OMG_HALP_ME_BUDS!!!!!!!!!!!!!!1111111oneoneoneeleven"),
                                new Shoot(0, 2, shootAngle: 10, projectileIndex: 1, fixedAngle: 45),
                                new Shoot(0, 2, shootAngle: 10, projectileIndex: 1, fixedAngle: 135),
                                new Shoot(0, 2, shootAngle: 10, projectileIndex: 1, fixedAngle: 225),
                                new Shoot(0, 2, shootAngle: 10, projectileIndex: 1, fixedAngle: 315),
                                new TimedTransition(800, "shoot3")
                            ),
                            new State("shoot3",
                                new HpLessTransition(0.2, "OMG_HALP_ME_BUDS!!!!!!!!!!!!!!1111111oneoneoneeleven"),
                                new Shoot(0, 2, shootAngle: 15, projectileIndex: 1, fixedAngle: 45),
                                new Shoot(0, 2, shootAngle: 15, projectileIndex: 1, fixedAngle: 135),
                                new Shoot(0, 2, shootAngle: 15, projectileIndex: 1, fixedAngle: 225),
                                new Shoot(0, 2, shootAngle: 15, projectileIndex: 1, fixedAngle: 315),
                                new TimedTransition(800, "shoot1")
                            )
                        )
                    ),
                    new State("OMG_HALP_ME_BUDS!!!!!!!!!!!!!!1111111oneoneoneeleven",
                        new Order(100, "vlntns Bella Buds", "CUTIES_PROTECT_ME"),
                        new Taunt(1, true, "My children...Aid me..."),
                        new Shoot(10, count: 6, projectileIndex: 3),
                        new Shoot(10, count: 3, shootAngle: 15, predictive: 0.7, coolDown: 1000),
                        new State("shoot1",
                            new Shoot(0, projectileIndex: 3, fixedAngle: 45),
                            new Shoot(0, projectileIndex: 3, fixedAngle: 135),
                            new Shoot(0, projectileIndex: 3, fixedAngle: 225),
                            new Shoot(0, projectileIndex: 3, fixedAngle: 315),
                            new TimedTransition(1000, "shoot2")
                        ),
                        new State("shoot2",
                            new Shoot(0, 2, shootAngle: 15, projectileIndex: 3, fixedAngle: 45),
                            new Shoot(0, 2, shootAngle: 15, projectileIndex: 3, fixedAngle: 135),
                            new Shoot(0, 2, shootAngle: 15, projectileIndex: 3, fixedAngle: 225),
                            new Shoot(0, 2, shootAngle: 15, projectileIndex: 3, fixedAngle: 315),
                            new TimedTransition(1000, "shoot1")
                        )
                    )
                )
            )
            .Init("vlntns Bella Buds",
                new State(
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable, true),
                    new EntityNotExistsTransition("vlntns Botany Bella", 100, "Despawn"),
                    new State("I_WILL_HALP_YOU_BUD_<3",
                        new State("IMMA_MOVE_NAOW",
                            new Follow(1, range: 1),
                            new PlayerWithinTransition(1, "IMMA_DONT_MOVE_NAOW"),
                            new State("shoot1",
                                new Shoot(10, fixedAngle: 145),
                                new TimedTransition(333, "shoot2")
                            ),
                            new State("shoot2",
                                new Shoot(10, fixedAngle: 265),
                                new TimedTransition(333, "shoot3")
                            ),
                            new State("shoot3",
                                new Shoot(10, fixedAngle: 385),
                                new TimedTransition(333, "shoot1")
                            )
                        ),
                        new State("IMMA_DONT_MOVE_NAOW",
                            new TimedTransition(2000, "IMMA_MOVE_NAOW"),
                            new State("shoot1",
                                new Shoot(10, fixedAngle: 145),
                                new TimedTransition(333, "shoot2")
                            ),
                            new State("shoot2",
                                new Shoot(10, fixedAngle: 265),
                                new TimedTransition(333, "shoot3")
                            ),
                            new State("shoot3",
                                new Shoot(10, fixedAngle: 385),
                                new TimedTransition(333, "shoot1")
                            )
                        )
                    ),
                    new State("CUTIES_PROTECT_ME",
                        new Orbit(0.7, 1, target: "vlntns Botany Bella", radiusVariance: 1),
                        new Shoot(10, coolDown: 2000)
                    ),
                    new State("Despawn",
                        new Timed(1000, new Suicide())
                    )
                )
            )
            .Init("vlntns Red",
                new State(
                    new EntityNotExistsTransition("vlntns Botany Bella", 50, "Despawn"),
                    new State("SleepForASec",
                        new EntityNotExistsTransition("vlntns White", 50, "Imma_Full_of_POWAAA"),
                        new TimedTransition(1000, "Imma_Full_of_POWAAA")
                    ),
                    new State("Imma_Full_of_POWAAA",
                        new Shoot(20, 6, coolDown: 1000),
                        new TransformOnDeath("vlntns White"),
                        new State(
                            new State("tex1",
                                new SetAltTexture(1),
                                new TimedTransition(1000, "tex2")
                            ),
                            new State("tex2",
                                new SetAltTexture(2),
                                new TimedTransition(1000, "tex2")
                            ),
                            new State("tex3",
                                new SetAltTexture(3)
                            )
                        )
                    ),
                    new State("Despawn",
                        new Timed(1000, new Suicide())
                    )
                )
            )
            .Init("vlntns White",
                new State(
                    new EntityNotExistsTransition("vlntns Botany Bella", 50, "Despawn"),
                    new State("SleepForASec",
                        new EntityNotExistsTransition("vlntns Yellow", 50, "Imma_Full_of_POWAAA"),
                        new TimedTransition(1000, "Imma_Full_of_POWAAA")
                    ),
                    new State("Imma_Full_of_POWAAA",
                        new Shoot(20, 6, coolDown: 1000),
                        new TransformOnDeath("vlntns Yellow"),
                        new State(
                            new State("tex1",
                                new SetAltTexture(1),
                                new TimedTransition(1000, "tex2")
                            ),
                            new State("tex2",
                                new SetAltTexture(2),
                                new TimedTransition(1000, "tex2")
                            ),
                            new State("tex3",
                                new SetAltTexture(3)
                            )
                        )
                    ),
                    new State("Despawn",
                        new Timed(1000, new Suicide())
                    )
                )
            )
            .Init("vlntns Yellow",
                new State(
                    new EntityNotExistsTransition("vlntns Botany Bella", 50, "Despawn"),
                    new State("SleepForASec",
                        new EntityNotExistsTransition("vlntns Red", 50, "Imma_Full_of_POWAAA"),
                        new TimedTransition(1000, "Imma_Full_of_POWAAA")
                    ),
                    new State("Imma_Full_of_POWAAA",
                        new Shoot(20, 6, coolDown: 1000),
                        new TransformOnDeath("vlntns Red"),
                        new State(
                            new State("tex1",
                                new SetAltTexture(1),
                                new TimedTransition(1000, "tex2")
                            ),
                            new State("tex2",
                                new SetAltTexture(2),
                                new TimedTransition(1000, "tex2")
                            ),
                            new State("tex3",
                                new SetAltTexture(3)
                            )
                        )
                    ),
                    new State("Despawn",
                        new Timed(1000, new Suicide())
                    )
                )
            )
            .Init("Thessal the Mermaid Goddess",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new Wander(0.22),
                        new TimedTransition(6000, "Fight")
                    ),
                    new State("Fight",
                    new Wander(0.22),
                    new Shoot(25, projectileIndex: 0, count: 12, shootAngle: 30, coolDown: 4000, coolDownOffset: 400), //armorbreak
                    new Shoot(25, projectileIndex: 1, count: 1, coolDown: 200), //trident
                    new Shoot(25, projectileIndex: 2, count: 5, shootAngle: 12, predictive: 0.4, coolDown: 2000), //supertrident
                    new Shoot(25, projectileIndex: 3, count: 20, shootAngle: 18, fixedAngle: 0, coolDownOffset: 3000, coolDown: 5000) //weaken
                    )
                ),
                new Threshold(0.001,
                new ItemLoot("Poseidon's Trident", 0.0005),
                new ItemLoot("Robe of the Draconic Overlord", 0.005),
                new ItemLoot("Flames of Purity", 0.01),
                new ItemLoot("Covering of Mermaid Goddess", 0.01),
                new ItemLoot("Radiant Wand of Royalism", 0.01),
                new ItemLoot("Oceanic Treasure", 0.04),
                new ItemLoot("Coral Bow", 0.05),
                new ItemLoot("Coral Venom Trap", 0.05),
                new ItemLoot("Coral Silk Armor", 0.08),
                new ItemLoot("Coral Ring", 0.1),
                new ItemLoot("Potion of Mana", 1),
                new ItemLoot("Potion of Mana", 0.25),
                new ItemLoot("Potion of Wisdom", 0.25),
                new ItemLoot("Potion of Attack", 0.25),
                new EggLoot(EggRarity.Common, 0.1),
                new EggLoot(EggRarity.Uncommon, 0.05),
                new EggLoot(EggRarity.Rare, 0.01),
                new EggLoot(EggRarity.Legendary, 0.001)
                )
            )
            .Init("Coral Gift",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(3000, "CGift")
                    ),
                    new State("CGift")
                ),
                new Threshold(0.001,
                new ItemLoot("Poseidon's Trident", 0.0001),
                new ItemLoot("Robe of the Draconic Overlord", 0.001),
                new ItemLoot("Flames of Purity", 0.003),
                new ItemLoot("Covering of Mermaid Goddess", 0.003),
                new ItemLoot("Radiant Wand of Royalism", 0.003),
                new ItemLoot("Oceanic Treasure", 0.022),
                new ItemLoot("Coral Bow", 0.033),
                new ItemLoot("Coral Venom Trap", 0.033),
                new ItemLoot("Coral Silk Armor", 0.06),
                new ItemLoot("Coral Ring", 0.08),
                new ItemLoot("Potion of Mana", 0.25),
                new ItemLoot("Potion of Wisdom", 0.25),
                new ItemLoot("Coral Juice", 0.5),
                new EggLoot(EggRarity.Common, 0.1),
                new EggLoot(EggRarity.Uncommon, 0.05),
                new EggLoot(EggRarity.Rare, 0.01),
                new EggLoot(EggRarity.Legendary, 0.001)
                )
            )
            .Init("Cosmic Mixup Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(5000, "HF")
                    ),
                    new State("HF")
                ),
                new Threshold(0.001,
                new ItemLoot("Z Saber", 0.0005),
                new ItemLoot("Ultimate Bracer", 0.0005),
                new ItemLoot("Ultimate Gemstone", 0.0005),
                new ItemLoot("Ultimate Crown", 0.0005),
                new ItemLoot("Purity", 0.0005),
                new ItemLoot("Handcannon", 0.0005),
                new ItemLoot("Staff of Annihilation", 0.0005),
                new ItemLoot("Soulfester", 0.0005),
                new ItemLoot("Amulet of Ascension", 0.0005),
                new ItemLoot("Raven's Personal Bow", 0.0005),
                new ItemLoot("Lucky Slasher", 0.0005),
                new ItemLoot("Karen Jacket", 0.0005),
                new ItemLoot("Elicia Blanket", 0.0005),
                new ItemLoot("Ji Robe", 0.0006),
                new ItemLoot("Boshy Gun", 0.0005),
                new ItemLoot("Butcher's Plate", 0.0005),
                new ItemLoot("Breastplate of the Plague", 0.0005),
                new ItemLoot("Top Hat", 0.0005),
                new ItemLoot("The Oddishclaw", 0.0005),
                new ItemLoot("Crown of the Universe", 0.0005),
                new ItemLoot("Blondie's Claws", 0.0005),
                new ItemLoot("Eternal Love", 0.0005),
                new ItemLoot("Snare of the Lurking Titan", 0.0005),
                new ItemLoot("Wand of the Galaxy", 0.0005),
                new ItemLoot("Old Farmer's Leather Book", 0.0005),
                new ItemLoot("Quasar Piercer", 0.0005),
                new ItemLoot("Poseidon's Trident", 0.0005)
                )
            )
            .Init("Evil Fake Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(5000, "DIE")
                    ),
                    new State("DIE",
                    new Taunt("Get trolled."),
                    new Shoot(25, projectileIndex: 0, count: 60, shootAngle: 6, fixedAngle: 1, coolDown: 200),
                    new Shoot(25, projectileIndex: 0, count: 60, shootAngle: 6, fixedAngle: 4, coolDown: 200, coolDownOffset: 100),
                    new ConditionalEffect(ConditionEffectIndex.Armored)
                    )
                ),
                new Threshold(0.001,
                new ItemLoot("Z Saber", 0.0005),
                new ItemLoot("Ultimate Bracer", 0.0005),
                new ItemLoot("Ultimate Gemstone", 0.0005),
                new ItemLoot("Ultimate Crown", 0.0005),
                new ItemLoot("Purity", 0.0005),
                new ItemLoot("Handcannon", 0.0005),
                new ItemLoot("Staff of Annihilation", 0.0005),
                new ItemLoot("Soulfester", 0.0005),
                new ItemLoot("Amulet of Ascension", 0.0005),
                new ItemLoot("Raven's Personal Bow", 0.0005),
                new ItemLoot("Lucky Slasher", 0.0005),
                new ItemLoot("Karen Jacket", 0.0005),
                new ItemLoot("Elicia Blanket", 0.0005),
                new ItemLoot("Ji Robe", 0.0005),
                new ItemLoot("Boshy Gun", 0.0005),
                new ItemLoot("Butcher's Plate", 0.0005),
                new ItemLoot("Breastplate of the Plague", 0.0005),
                new ItemLoot("Top Hat", 0.0005),
                new ItemLoot("The Oddishclaw", 0.0005),
                new ItemLoot("Crown of the Universe", 0.0005),
                new ItemLoot("Blondie's Claws", 0.0005),
                new ItemLoot("Eternal Love", 0.0005),
                new ItemLoot("Snare of the Lurking Titan", 0.0005),
                new ItemLoot("Wand of the Galaxy", 0.0005),
                new ItemLoot("Old Farmer's Leather Book", 0.0005),
                new ItemLoot("Quasar Piercer", 0.0005),
                new ItemLoot("Poseidon's Trident", 0.0005)
                )
            )
            .Init("Final Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(25000, "Loot")
                    ),
                    new State("Loot")
                ),
                new Threshold(0.001,
                new ItemLoot("Elithor's Soul Bottle", 0.004),
                new ItemLoot("Snowstorm Armor", 0.005),
                new ItemLoot("Mysterious Totem", 0.01),
                new ItemLoot("Magical Incantation", 0.01),
                new ItemLoot("Deception", 0.01),
                new ItemLoot("Heart of the Mountains", 0.01),
                new ItemLoot("Strike Amulet", 0.025),
                new ItemLoot("Raven's Personal Bow", 0.0003),
                new ItemLoot("Poniard of Ghastly Retribution", 0.004),
                new ItemLoot("Odin's Attire", 0.01),
                new ItemLoot("Zol Elixir", 0.01),
                new ItemLoot("Flaming Armor of Magma", 0.05),
                new ItemLoot("Trap of the Vile Spirit", 0.05),
                new ItemLoot("Pirate King's Cutlass", 0.05),
                new ItemLoot("Sor Reactor", 0.004),
                new ItemLoot("Cyber Soldier Helm", 0.005),
                new ItemLoot("Hela's Robe", 0.01),
                new ItemLoot("Wand of the Ascended Creation", 0.012),
                new ItemLoot("Gargoyle Stoneplate", 0.01),
                new ItemLoot("Short Circuit", 0.05),
                new ItemLoot("Scepter of Fulmination", 0.05),
                new ItemLoot("Conducting Wand", 0.04),
                new ItemLoot("Robe of the Mad Scientist", 0.05),
                new ItemLoot("Experimental Ring", 0.10),
                new ItemLoot("Necklace of Undead Support", 0.01),
                new ItemLoot("Butcher's Plate", 0.0003),
                new ItemLoot("Orb of Destiny", 0.004),
                new ItemLoot("Death's Mantle", 0.004),
                new ItemLoot("Kiskiorab", 0.01),
                new ItemLoot("Master of the House", 0.01),
                new ItemLoot("Water Dragon Silk Robe", 0.05),
                    new ItemLoot("Lucky Slasher", 0.0003),
                    new ItemLoot("Gravachrome", 0.004),
                    new ItemLoot("Thusala's Slasher", 0.0038),
                    new ItemLoot("Queen's Crown", 0.01),
                    new ItemLoot("Garbs of the Frozen Queen", 0.01),
                    new ItemLoot("Shield of Ogmur", 0.04),
                    new ItemLoot("Frosty's Walking Stick", 0.05),
                new ItemLoot("Cloak of Vampirism", 0.004),
                new ItemLoot("Flame of Misery", 0.004),
                new ItemLoot("Odin's Ravens", 0.01),
                new ItemLoot("Undead's Gross Bow", 0.009),
                new ItemLoot("Carrier's Suit", 0.01),
                new ItemLoot("Sincryer's Demise", 0.01),
                new ItemLoot("Soul's Guidance", 0.05),
                new ItemLoot("Plague Poison", 0.05),
                new ItemLoot("Resurrected Warrior's Armor", 0.05),
                new ItemLoot("Etherite Dagger", 0.03),
                new ItemLoot("Ghastly Drape", 0.04),
                new ItemLoot("Mantle of Skuld", 0.04),
                new ItemLoot("Spectral Ring of Horrors", 0.04),
                new ItemLoot("Yeti Walkers", 0.004),
                new ItemLoot("Thunderfall's Storm", 0.01),
                new ItemLoot("Penetrating Blast Spell", 0.04),
                new ItemLoot("Sandstone Seal", 0.05),
                new ItemLoot("Peppermint Candy Bow", 0.0072),
                new ItemLoot("Festive Quiver", 0.0076),
                new ItemLoot("Elf Suit", 0.0078),
                new ItemLoot("Merrystone", 0.0078),
                new ItemLoot("Star of the North Pole", 0.009),
                new ItemLoot("Wand of Ornaments", 0.009),
                new ItemLoot("North Pole's Slasher", 0.009),
                new ItemLoot("North Pole's Orb", 0.009),
                new ItemLoot("Chocolate Cookie", 0.009),
                new ItemLoot("Robe of Celebration", 0.009),
                new ItemLoot("Santa's Battle Attire", 0.009),
                new ItemLoot("Kurisumasu no Uwagi", 0.009),
                new ItemLoot("Santa's Coat", 0.009),
                new ItemLoot("Santa Hat", 0.009),
                new ItemLoot("Santa's Mitten", 0.009),
                new ItemLoot("Ring of the New Sun", 0.009),
                new ItemLoot("Blondie's Claws", 0.0003),
                new ItemLoot("Morningstar of Honey", 0.004),
                new ItemLoot("Ring of the Cosmos", 0.004),
                new ItemLoot("Bee Wand", 0.01),
                new ItemLoot("Beehemoth Quiver Yellow", 0.025),
                new ItemLoot("Beehemoth Quiver Blue", 0.025),
                new ItemLoot("Beehemoth Quiver Red", 0.025),
                new ItemLoot("Bottle of Condensed Honey", 0.045),
                new ItemLoot("Queen's Stinger Dagger", 0.045),
                new ItemLoot("Hivemaster Helm", 0.045),
                new ItemLoot("Nectar Crossfire", 0.05),
                new ItemLoot("Honeytomb Snare", 0.05),
                new ItemLoot("Honey Circlet", 0.05),
                new ItemLoot("Beehemoth Armor Yellow", 0.03),
                new ItemLoot("Beehemoth Armor Blue", 0.03),
                new ItemLoot("Beehemoth Armor Red", 0.03),
                new ItemLoot("Honey Scepter", 0.05),
                new ItemLoot("Orb of Sweet Demise", 0.05),
                new ItemLoot("Wand of the Galaxy", 0.0003),
                new ItemLoot("Crown of the Universe", 0.00028),
                new ItemLoot("Plasma Bee Wand", 0.01),
                new ItemLoot("Beacon of Light", 0.01),
                new ItemLoot("Laser Gun", 0.01),
                new ItemLoot("Lightsaber", 0.01),
                new ItemLoot("Star of Light", 0.01),
                new ItemLoot("Lightshow", 0.01),
                new ItemLoot("Old Farmer's Leather Book", 0.0003),
                new ItemLoot("Page of Catatonia", 0.004),
                new ItemLoot("March of the Army", 0.01),
                new ItemLoot("Cow Horns", 0.05),
                new ItemLoot("Cow Skin Shield", 0.05),
                new ItemLoot("Milky Orb", 0.05),
                new ItemLoot("Soulfester", 0.0003),
                new ItemLoot("Ghost Robe", 0.004),
                new ItemLoot("Scythe of Death", 0.004),
                new ItemLoot("Gileon's Spirit", 0.004),
                new ItemLoot("Harlequin's Crossbow", 0.01),
                new ItemLoot("Cloak of Bloody Surprises", 0.04),
                new ItemLoot("Handcannon", 0.0003),
                new ItemLoot("Sword of Oryx", 0.004),
                new ItemLoot("Helm of Oryx", 0.004),
                new ItemLoot("Armor of Oryx", 0.004),
                new ItemLoot("Ring of Oryx", 0.004),
                new ItemLoot("Saturn's Orbit", 0.004),
                new ItemLoot("Vulcanstriker", 0.01),
                new ItemLoot("Thousand Shot", 0.05),
                new ItemLoot("Sword of the Mad God", 0.03),
                new ItemLoot("Onyx Shield of the Mad God", 0.03),
                new ItemLoot("Almandine Armor of Anger", 0.03),
                new ItemLoot("Almandine Ring of Wrath", 0.03),
                new ItemLoot("Backpack", 0.15),
                new ItemLoot("Boshy Gun", 0.0003),
                new ItemLoot("Harbinger of Fury", 0.004),
                new ItemLoot("Oryx's Decapitator", 0.004),
                new ItemLoot("Seal of Oryx", 0.004),
                new ItemLoot("Vanguard of Oryx", 0.004),
                new ItemLoot("Amulet of Pure Madness", 0.004),
                new ItemLoot("The Twilight Grimoire", 0.004),
                new ItemLoot("Jackpot", 0.01),
                new ItemLoot("Captain America Sword", 0.05),
                new ItemLoot("Band of Oryx", 0.05),
                new ItemLoot("Titan's Breastplate", 0.005),
                new ItemLoot("Cloak of Terradius", 0.015),
                new ItemLoot("Ruby Plated Armor", 0.015),
                new ItemLoot("Gauntlet of Mortality", 0.015),
                new ItemLoot("Ancient Stone Sword", 0.07),
                new ItemLoot("Ivory Ring", 0.06),
                new ItemLoot("Purity", 0.0003),
                new ItemLoot("Claw of the Beast", 0.004),
                new ItemLoot("Cosmic Cortex", 0.005),
                new ItemLoot("Death's Gem", 0.01),
                new ItemLoot("Rabbit's Foot", 0.01),
                new ItemLoot("Lycaon's Hide", 0.004),
                new ItemLoot("Staff of Demonic Power", 0.01),
                new ItemLoot("Hellfire Orb", 0.01),
                new ItemLoot("The Scorched Armor", 0.05),
                new ItemLoot("Prism of Dancing Swords", 0.05),
                new ItemLoot("Staff of the Rising Sun", 0.05),
                new ItemLoot("Ring of the Burning Sun", 0.05),
                new ItemLoot("Clarent", 0.004),
                new ItemLoot("Bloodlord's Cranium", 0.004),
                new ItemLoot("Lycaon's Heart", 0.004),
                new ItemLoot("Head of the Firebreather", 0.01),
                new ItemLoot("Ring of Solar Focus", 0.01),
                new ItemLoot("Skull of Endless Torment", 0.05),
                new ItemLoot("Fire Dragon Battle Armor", 0.05),
                new ItemLoot("Ultimate Crown", 0.0003),
                new ItemLoot("Staff of Annihilation", 0.0003),
                new ItemLoot("The Forsaken Ring", 0.0045),
                new ItemLoot("Cloak of the King", 0.0048),
                new ItemLoot("Hela's Essence", 0.0045),
                new ItemLoot("King's Crossbow", 0.01),
                new ItemLoot("Forgotten Robe", 0.01),
                new ItemLoot("The Great Lightsword", 0.01),
                new ItemLoot("Grey Belt", 0.01),
                new ItemLoot("The Forgotten Crown", 0.04),
                new ItemLoot("Ancient Spell: Pierce", 0.04),
                new ItemLoot("Ultimate Gemstone", 0.0003),
                new ItemLoot("Quasar Piercer", 0.0003),
                new ItemLoot("Greatcloak of Twilight", 0.004),
                new ItemLoot("Wand of Bone", 0.004),
                new ItemLoot("Malevolent Armor", 0.004),
                new ItemLoot("Hela's Horns", 0.01),
                new ItemLoot("Crown of the Elements", 0.01),
                new ItemLoot("The Twilight Gemstone", 0.04),
                new ItemLoot("Sentient Staff", 0.04),
                new ItemLoot("The Robe of Twilight", 0.04),
                new ItemLoot("Ultimate Bracer", 0.0003),
                new ItemLoot("Blades of the Bridge", 0.004),
                new ItemLoot("Bel's Decapitator", 0.004),
                new ItemLoot("Bracer of the Guardian", 0.04),
                new ItemLoot("The Forgotten Ring", 0.04),
                new ItemLoot("Limbsplit Quiver", 0.004),
                new ItemLoot("Malignant Slasher", 0.009),
                new ItemLoot("Cytoplasmic Induced Leather", 0.01),
                new ItemLoot("Samurai's Belt", 0.01),
                new ItemLoot("Sensei's Hat", 0.01),
                new ItemLoot("The Scavenger's Attire", 0.04),
                new ItemLoot("Wand of the Bulwark", 0.05),
                new ItemLoot("Snake Skin Shield", 0.10),
                new ItemLoot("Snake Skin Armor", 0.10),
                new ItemLoot("Snake Eye Ring", 0.10),
                new ItemLoot("Helm of the Necropolis", 0.004),
                new ItemLoot("Star of Bones", 0.004),
                new ItemLoot("Bloodstone of Enmity", 0.009),
                new ItemLoot("Burning Sun Scepter", 0.01),
                new ItemLoot("Drannol's Spirit", 0.01),
                new ItemLoot("Ancient Pendant", 0.01),
                new ItemLoot("Platinum Argarius", 0.01),
                new ItemLoot("Helm of the Juggernaut", 0.04),
                new ItemLoot("Robe of the Summer Solstice", 0.05),
                new ItemLoot("Reaper's Bow", 0.004),
                new ItemLoot("Predator Necklace", 0.01),
                new ItemLoot("Poison Fang Dagger", 0.10),
                new ItemLoot("Spider's Eye Ring", 0.10),
                new ItemLoot("Elicia Blanket", 0.0003),
                new ItemLoot("Ring of Fleshly Desires", 0.004),
                new ItemLoot("Dagger of the Endless Void", 0.0011),
                new ItemLoot("Wheel of Flames", 0.01),
                new ItemLoot("Cloak of the Planewalker", 0.04),
                new ItemLoot("Planewalker Armor", 0.04),
                new ItemLoot("Staff of Extreme Prejudice", 0.05),
                new ItemLoot("Rigormortis", 0.004),
                new ItemLoot("Bonesplinter Robe", 0.004),
                new ItemLoot("Buckler of the Ancients", 0.01),
                new ItemLoot("Seal of Glowing Honor", 0.01),
                new ItemLoot("Drannol's Judgement", 0.01),
                new ItemLoot("Blade of the Fallen Sky", 0.04),
                new ItemLoot("Ring of the Pyramid", 0.05),
                new ItemLoot("Tome of Holy Protection", 0.05),
                new ItemLoot("Eternal Love", 0.0003),
                new ItemLoot("Blessed Ring of the Tomb", 0.005),
                new ItemLoot("Gungnir", 0.009),
                new ItemLoot("Ancient Longbow", 0.01),
                new ItemLoot("Staff of Royal Revenge", 0.01),
                new ItemLoot("Lightning God Ring", 0.05),
                new ItemLoot("Ring of the Nile", 0.05),
                new ItemLoot("Amulet of the Ancients", 0.01),
                new ItemLoot("Garbs of the Sun God", 0.01),
                new ItemLoot("Gemstone of Divinity", 0.01),
                new ItemLoot("Attire of Chaos", 0.01),
                new ItemLoot("Ring of the Sphinx", 0.05),
                new ItemLoot("Wand of Geb", 0.04),
                new ItemLoot("Book of Geb", 0.04),
                new ItemLoot("Shendyt of Geb", 0.04),
                new ItemLoot("Geb's Ring of Wisdom", 0.04),
                new ItemLoot("Boneshatter", 0.004),
                new ItemLoot("Ectoplasm Blade", 0.005),
                new ItemLoot("Soulkeeper", 0.01),
                new ItemLoot("Mercy of Yazanahar", 0.01),
                new ItemLoot("Shattered War Axe", 0.01),
                new ItemLoot("Spectral Armor", 0.04),
                new ItemLoot("Doom Bow", 0.05),
                new ItemLoot("The Necronomicon", 0.05),
                new ItemLoot("Bow of the Morning Star", 0.02),
                new ItemLoot("Dreadcool", 0.001),
                new ItemLoot("Dreadcull", 0.004),
                new ItemLoot("Nightmare Gem", 0.004),
                new ItemLoot("The Apex Bulwark", 0.004),
                new ItemLoot("Skull of Ravagers", 0.01),
                new ItemLoot("Dirk of Notorious Agents", 0.01),
                new ItemLoot("Zol Wraps", 0.01),
                new ItemLoot("Force Between Avex", 0.01),
                new ItemLoot("Unholy Short Sword", 0.03),
                new ItemLoot("Seal of Blasphemous Prayer", 0.04),
                new ItemLoot("Annoying Firecracker Katana", 0.05),
                new ItemLoot("Skull of the Light Lord", 0.01),
                new ItemLoot("Hide of Light", 0.01),
                new ItemLoot("Light Core", 0.01),
                new ItemLoot("Light's Orbit", 0.01),
                new ItemLoot("Plasmastone", 0.01),
                new ItemLoot("Plasma Sprout", 0.01),
                new ItemLoot("Tablet of Doom", 0.012),
                new ItemLoot("Starcrash Ring", 0.025),
                new ItemLoot("Snare of the Lurking Titan", 0.0005),
                new ItemLoot("Omnipotence Ring", 0.004),
                new ItemLoot("Sword of the Colossus", 0.01),
                new ItemLoot("Marble Seal", 0.01),
                new ItemLoot("Breastplate of New Life", 0.01),
                new ItemLoot("Magical Lodestone", 0.01),
                new ItemLoot("Bow of the Void", 0.01),
                new ItemLoot("Quiver of the Shadows", 0.01),
                new ItemLoot("Armor of Nil", 0.01),
                new ItemLoot("Sourcestone", 0.01),
                new ItemLoot("Staff of Unholy Sacrifice", 0.01),
                new ItemLoot("Skull of Corrupted Souls", 0.01),
                new ItemLoot("Ritual Robe", 0.01),
                new ItemLoot("Bloodshed Ring", 0.01),
                new ItemLoot("Forest Parry Technique", 0.01),
                new ItemLoot("Petrified Lophop", 0.01),
                new ItemLoot("Unholy Spell", 0.04),
                new ItemLoot("Bubble Discharger Staff", 0.01),
                new ItemLoot("Robes of Aldragine", 0.01),
                new ItemLoot("Midnight Star", 0.05),
                new ItemLoot("Void Blade", 0.05),
                new ItemLoot("pD Armor", 0.05),
                new ItemLoot("Atonement", 0.004),
                new ItemLoot("Blazing Machete", 0.004),
                new ItemLoot("Necrotic Boneplate", 0.004),
                new ItemLoot("Crown of War", 0.0098),
                new ItemLoot("Demon Summoning Tome", 0.01),
                new ItemLoot("The Infernus", 0.01),
                new ItemLoot("Orb of Conflict", 0.05),
                new ItemLoot("Hell's Breastplate", 0.04),
                new ItemLoot("Flaming Boomerang", 0.05),
                new ItemLoot("Z Saber", 0.0003),
                new ItemLoot("Larry Gun", 0.004),
                new ItemLoot("The Rainstorm", 0.01),
                new ItemLoot("Helm of Erebus", 0.01),
                new ItemLoot("Octopussy", 0.01),
                new ItemLoot("Helm of the Juggernaut", 0.05),
                new ItemLoot("Flesh Trap", 0.004),
                new ItemLoot("Helldom Shell", 0.004),
                new ItemLoot("Demon Lord's Wrath", 0.005),
                new ItemLoot("Robe of Bloodbath", 0.01),
                new ItemLoot("Abaddon's Bracelet", 0.01),
                new ItemLoot("Hellstone", 0.01),
                new ItemLoot("Burning Tome", 0.01),
                new ItemLoot("Destructor Armor", 0.05),
                new ItemLoot("Ring of the Demon Lord", 0.05),
                new ItemLoot("Demon Blade", 0.05),
                new ItemLoot("Sword of Illumination", 0.02),
                new ItemLoot("Thousand Suns Spell", 0.05),
                new ItemLoot("Cursed Wand of the Corrupted", 0.004),
                new ItemLoot("Favor of Fortune", 0.004),
                new ItemLoot("Necklace of Fangs", 0.004),
                new ItemLoot("The Forgotten Conduit", 0.009),
                new ItemLoot("Cremation", 0.01),
                new ItemLoot("The Executioner", 0.01),
                new ItemLoot("Sons Sparkling", 0.04),
                new ItemLoot("Tablet of the King's Avatar", 0.05),
                new ItemLoot("Pizza Ring", 0.05),
                new ItemLoot("Ji Robe", 0.0003),
                new ItemLoot("Candy-Coated Armor", 0.05),
                new ItemLoot("Pixie-Enchanted Sword", 0.02),
                new ItemLoot("Seal of the Enchanted Forest", 0.03),
                new ItemLoot("Fairy Plate", 0.03),
                new ItemLoot("Ring of Pure Wishes", 0.03),
                new ItemLoot("Candy Ring", 0.1),
                new ItemLoot("Bonemail of the Fallen", 0.004),
                new ItemLoot("Candy-Coated Armor", 0.05),
                new ItemLoot("Pixie-Enchanted Sword", 0.02),
                new ItemLoot("Seal of the Enchanted Forest", 0.03),
                new ItemLoot("Fairy Plate", 0.03),
                new ItemLoot("Ring of Pure Wishes", 0.03),
                new ItemLoot("Candy Ring", 0.1),
                new ItemLoot("Harbinger", 0.004),
                new ItemLoot("Insurgency Amulet", 0.01),
                new ItemLoot("Candy-Coated Armor", 0.05),
                new ItemLoot("Pixie-Enchanted Sword", 0.02),
                new ItemLoot("Seal of the Enchanted Forest", 0.03),
                new ItemLoot("Fairy Plate", 0.03),
                new ItemLoot("Ring of Pure Wishes", 0.03),
                new ItemLoot("Candy Ring", 0.1),
                new ItemLoot("Super Mushroom", 0.04),
                new ItemLoot("Harlequin Armor", 0.05),
                new ItemLoot("Candy Ring", 0.15),
                new ItemLoot("Karen Jacket", 0.0003),
                new ItemLoot("Essence of Death", 0.004),
                new ItemLoot("Phantom Cleaver", 0.004),
                new ItemLoot("Tome of Fleshly Desires", 0.004),
                new ItemLoot("The Gravedigger's Disguise", 0.01),
                new ItemLoot("Dirk of Cronus", 0.05),
                new ItemLoot("Amulet of Ascension", 0.0003),
                new ItemLoot("Unstable Jewel", 0.004),
                new ItemLoot("Frozen Time", 0.005),
                new ItemLoot("Scorching Refraction", 0.01),
                new ItemLoot("Enchanted Uru Sword", 0.0095),
                new ItemLoot("Winds of Change", 0.01),
                new ItemLoot("Gemstone Attire", 0.01),
                new ItemLoot("Robe of Majesty", 0.01),
                new ItemLoot("Purification Crystal", 0.01),
                new ItemLoot("Forgotten Zol Gem", 0.01),
                new ItemLoot("MC Irons Shield", 0.04),
                new ItemLoot("Crystal Sword", 0.05),
                new ItemLoot("Crystal Wand", 0.05),
                new ItemLoot("Wall of Gore", 0.004),
                new ItemLoot("Vest of Doomed Souls", 0.004),
                new ItemLoot("Shadowsteel Plate", 0.005),
                new ItemLoot("Throwing Spear", 0.01),
                new ItemLoot("Bracelet of the Demolished", 0.01),
                new ItemLoot("Tome of Purification", 0.05),
                new ItemLoot("St. Abraham's Wand", 0.08),
                new ItemLoot("Bone Dagger", 0.08),
                new ItemLoot("Chasuble of Holy Light", 0.1),
                new ItemLoot("Ring of Divine Faith", 0.1),
                new ItemLoot("Soul Warden", 0.004),
                new ItemLoot("Seal of the Necropolis", 0.004),
                new ItemLoot("The Nuruaj", 0.01),
                new ItemLoot("The Darkin Skull", 0.01),
                new ItemLoot("Shiny Diver's Breastplate", 0.01),
                new ItemLoot("Entropy Reactor", 0.04),
                new ItemLoot("Orb of Aether", 0.045),
                new ItemLoot("Spirit Dagger", 0.05),
                new ItemLoot("Ghostly Prism", 0.05),
                new ItemLoot("Spectral Cloth Armor", 0.08),
                new ItemLoot("Captain's Ring", 0.10),
                new ItemLoot("Breastplate of the Plague", 0.0003),
                new ItemLoot("Skull of Vampirism", 0.004),
                new ItemLoot("The Gravedigger's Shovel", 0.009),
                new ItemLoot("Dagger of Tindailius", 0.01),
                new ItemLoot("Staff of Nature", 0.01),
                new ItemLoot("The Soul Ring", 0.01),
                new ItemLoot("Oblivion", 0.004),
                new ItemLoot("Scepter of the Ancients", 0.004),
                new ItemLoot("Amulet of the Underworld", 0.01),
                new ItemLoot("Star Ring", 0.01),
                new ItemLoot("Leaf Dragon Hide Armor", 0.05),
                new ItemLoot("Sewer Cocktail", 0.05),
                new ItemLoot("The Oddishclaw", 0.0003),
                new ItemLoot("Vinelocker", 0.004),
                new ItemLoot("The Soul Collector", 0.01),
                new ItemLoot("Speedier Sprout", 0.01),
                new ItemLoot("Gravachrome Grass", 0.004),
                new ItemLoot("Katana of Mythical Alliance", 0.01),
                new ItemLoot("Opus Salutem", 0.01),
                new ItemLoot("Butterfly Dagger", 0.01),
                new ItemLoot("Wing Necklace", 0.05),
                new ItemLoot("Leaf Bow", 0.05),
                new ItemLoot("Doku No Ken", 0.05),
                new ItemLoot("Poseidon's Trident", 0.0003),
                new ItemLoot("Robe of the Draconic Overlord", 0.005),
                new ItemLoot("Flames of Purity", 0.01),
                new ItemLoot("Covering of Mermaid Goddess", 0.01),
                new ItemLoot("Radiant Wand of Royalism", 0.01),
                new ItemLoot("Oceanic Treasure", 0.04),
                new ItemLoot("Coral Bow", 0.05),
                new ItemLoot("Coral Venom Trap", 0.05),
                new ItemLoot("Coral Silk Armor", 0.08),
                new ItemLoot("Coral Ring", 0.12)
                )
            )
            .Init("vlntns Loot Balloon Bella",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(5000, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                new Threshold(0.001,
                new ItemLoot("The Oddishclaw", 0.0005),
                new ItemLoot("Vinelocker", 0.004),
                new ItemLoot("The Soul Collector", 0.01),
                new ItemLoot("Speedier Sprout", 0.01),
                new ItemLoot("Path of Loot Key", 0.000125),
                new ItemLoot("Potion of Vitality", 0.66),
                new ItemLoot("Potion of Speed", 0.66),
                new ItemLoot("Potion of Wisdom", 0.55),
                new ItemLoot("Potion of Defense", 0.25),
                new ItemLoot("Diamond Bladed Katana", 0.15),
                new ItemLoot("Cupid's Bow", 0.15),
                new ItemLoot("Staff of Adoration", 0.15),
                new ItemLoot("Wand of Budding Romance", 0.15),
                new ItemLoot("Heartfind Dagger", 0.15),
                new ItemLoot("Vinesword", 0.15),
                new TierLoot(4, ItemType.Ability, 0.17),
                new TierLoot(5, ItemType.Ability, 0.17),
                new TierLoot(9, ItemType.Armor, 0.12),
                new TierLoot(10, ItemType.Armor, 0.12),
                new TierLoot(4, ItemType.Ring, 0.13),
                new TierLoot(5, ItemType.Ring, 0.13),
                new EggLoot(EggRarity.Common, 0.1),
                new EggLoot(EggRarity.Uncommon, 0.05),
                new EggLoot(EggRarity.Rare, 0.01),
                new EggLoot(EggRarity.Legendary, 0.001)
                )
            );
    }
}
