using wServer.logic.behaviors;
using wServer.logic.transitions;
using wServer.logic.loot;

namespace wServer.logic
{
    partial class BehaviorDb
    {
        private _ Chests = () => Behav()
            .Init("Omniversal Mixup Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(5000, "ooo")
                    ),
                    new State("ooo")
                ),
                new Threshold(0.001,
                new ItemLoot("Radiant Vanity", 0.0001),
                new ItemLoot("Boshy's Minigun", 0.0001),
                new ItemLoot("Staff of Drannol's Aura", 0.0001),
                new ItemLoot("Retro Clarent", 0.0001),
                new ItemLoot("The Dirk of Chickenslaying", 0.0001),
                new ItemLoot("The Realmdex", 0.0001),
                new ItemLoot("Cherry Jello", 0.0001),
                new ItemLoot("maiuash's Blessing", 0.0001),
                new ItemLoot("Mari's Vest", 0.0001),
                new ItemLoot("True Shielding of Oryx", 0.0001),
                new ItemLoot("Robe of Oddish", 0.0001),
                new ItemLoot("Admin Crown", 0.0001),
                new ItemLoot("The One True Ring", 0.0001),
                new ItemLoot("Giant Asian Hornet", 0.0001)
                )
            )
            .Init("Cosmic Mixup Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(5000, "HF")
                    ),
                    new State("HF")
                ),
                new Threshold(0.001,
                new ItemLoot("Handcannon", 0.0005),
                new ItemLoot("Staff of Annihilation", 0.0005),
                new ItemLoot("Soulfester", 0.0005),
                new ItemLoot("Amulet of Ascension", 0.0005),
                new ItemLoot("Lucky Slasher", 0.0005),
                new ItemLoot("Ultimate Bracer", 0.0005),
                new ItemLoot("Ultimate Gemstone", 0.0005),
                new ItemLoot("Ultimate Crown", 0.0005),
                new ItemLoot("Z Saber", 0.0005),
                new ItemLoot("Raven's Personal Bow", 0.0005),
                new ItemLoot("Boshy Gun", 0.0005),
                new ItemLoot("Karen Jacket", 0.0005),
                new ItemLoot("Elicia Blanket", 0.0005),
                new ItemLoot("Ji Robe", 0.0005),
                new ItemLoot("Purity", 0.0005),
                new ItemLoot("Breastplate of the Plague", 0.0005),
                new ItemLoot("The Oddishclaw", 0.0005),
                new ItemLoot("Top Hat", 0.0005),
                new ItemLoot("Crown of the Universe", 0.0005),
                new ItemLoot("Blondie's Claws", 0.0005),
                new ItemLoot("Butcher's Plate", 0.0005),
                new ItemLoot("Eternal Love", 0.0005),
                new ItemLoot("Wand of the Galaxy", 0.0005),
                new ItemLoot("Snare of the Lurking Titan", 0.0005),
                new ItemLoot("Quasar Piercer", 0.0005),
                new ItemLoot("Old Farmer's Leather Book", 0.0005),
                new ItemLoot("Poseidon's Trident", 0.0005),
                new ItemLoot("Whisper of the Seven Seas", 0.0005),
                new ItemLoot("Defender's Last Stand", 0.0005),
                new ItemLoot("Ceasar's Armor", 0.0005),
                new ItemLoot("The Realm Eye", 0.0005),
                new ItemLoot("Yukari Sakuragi's Umbrella", 0.0005),
                new ItemLoot("Mari's Spirit", 0.0005),
                new ItemLoot("Tsar Bomba", 0.0005),
                new ItemLoot("Cleopatra's Sheath", 0.0005),
                new ItemLoot("Mask of Thunders", 0.0005),
                new ItemLoot("Dice of the Royals", 0.0005),
                new ItemLoot("Deep Blue Anchor", 0.0005),
                new ItemLoot("Vengeance Helm", 0.0005),
                new ItemLoot("Mantle of the Departed", 0.0005),
                new ItemLoot("Reality Shift", 0.0005),
                new ItemLoot("Cape of the Observant", 0.0005),
                new ItemLoot("Orange Juice Robe", 0.0005),
                new ItemLoot("Cinderflame", 0.0005),
                new ItemLoot("True Dragon Imbued Seal", 0.0005),
                new ItemLoot("Volcano Fragment", 0.0005),
                new ItemLoot("A Following Phoenix", 0.0005)
                )
            )
            .Init("Evil Fake Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(5000, "DIE")
                    ),
                    new State("DIE",
                    new Taunt("Get trolled."),
                    new Shoot(25, projectileIndex: 0, count: 60, shootAngle: 6, fixedAngle: 1, coolDown: 400),
                    new Shoot(25, projectileIndex: 0, count: 60, shootAngle: 6, fixedAngle: 4, coolDown: 400, coolDownOffset: 200),
                    new ConditionalEffect(ConditionEffectIndex.Armored)
                    )
                ),
                new Threshold(0.001,
                new ItemLoot("Handcannon", 0.0005),
                new ItemLoot("Staff of Annihilation", 0.0005),
                new ItemLoot("Soulfester", 0.0005),
                new ItemLoot("Amulet of Ascension", 0.0005),
                new ItemLoot("Lucky Slasher", 0.0005),
                new ItemLoot("Ultimate Bracer", 0.0005),
                new ItemLoot("Ultimate Gemstone", 0.0005),
                new ItemLoot("Ultimate Crown", 0.0005),
                new ItemLoot("Z Saber", 0.0005),
                new ItemLoot("Raven's Personal Bow", 0.0005),
                new ItemLoot("Boshy Gun", 0.0005),
                new ItemLoot("Karen Jacket", 0.0005),
                new ItemLoot("Elicia Blanket", 0.0005),
                new ItemLoot("Ji Robe", 0.0005),
                new ItemLoot("Purity", 0.0005),
                new ItemLoot("Breastplate of the Plague", 0.0005),
                new ItemLoot("The Oddishclaw", 0.0005),
                new ItemLoot("Top Hat", 0.0005),
                new ItemLoot("Crown of the Universe", 0.0005),
                new ItemLoot("Blondie's Claws", 0.0005),
                new ItemLoot("Butcher's Plate", 0.0005),
                new ItemLoot("Eternal Love", 0.0005),
                new ItemLoot("Wand of the Galaxy", 0.0005),
                new ItemLoot("Snare of the Lurking Titan", 0.0005),
                new ItemLoot("Quasar Piercer", 0.0005),
                new ItemLoot("Old Farmer's Leather Book", 0.0005),
                new ItemLoot("Poseidon's Trident", 0.0005),
                new ItemLoot("Whisper of the Seven Seas", 0.0005),
                new ItemLoot("Defender's Last Stand", 0.0005),
                new ItemLoot("Ceasar's Armor", 0.0005),
                new ItemLoot("The Realm Eye", 0.0005),
                new ItemLoot("Yukari Sakuragi's Umbrella", 0.0005),
                new ItemLoot("Mari's Spirit", 0.0005),
                new ItemLoot("Tsar Bomba", 0.0005),
                new ItemLoot("Cleopatra's Sheath", 0.0005),
                new ItemLoot("Mask of Thunders", 0.0005),
                new ItemLoot("Dice of the Royals", 0.0005),
                new ItemLoot("Deep Blue Anchor", 0.0005),
                new ItemLoot("Vengeance Helm", 0.0005),
                new ItemLoot("Mantle of the Departed", 0.0005),
                new ItemLoot("Reality Shift", 0.0005),
                new ItemLoot("Cape of the Observant", 0.0005),
                new ItemLoot("Orange Juice Robe", 0.0005),
                new ItemLoot("Cinderflame", 0.0005),
                new ItemLoot("True Dragon Imbued Seal", 0.0005),
                new ItemLoot("Volcano Fragment", 0.0005),
                new ItemLoot("A Following Phoenix", 0.0005)
                )
            )
            .Init("Final Chest",
                new State(
                    new State("Idle",
                        new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                        new TimedTransition(15000, "Loot")
                    ),
                    new State("Loot")
                ),
                new Threshold(0.001,
                new ItemLoot("Philosopher's Stone", 0.01),
                new ItemLoot("Skystriker", 0.003),
                new ItemLoot("Trap Above the Clouds", 0.003),
                new ItemLoot("Wear of Angels", 0.003),
                new ItemLoot("Trinket of the Air", 0.003),
                new ItemLoot("Jon's Handcannon", 0.01),
                new ItemLoot("Oracle's Nightmare", 0.01),
                new ItemLoot("Elithor's Soul Bottle", 0.004),
                new ItemLoot("Snowstorm Armor", 0.005),
                new ItemLoot("Mysterious Totem", 0.01),
                new ItemLoot("Magical Incantation", 0.01),
                new ItemLoot("Words of Wisdom", 0.01),
                new ItemLoot("Deception", 0.01),
                new ItemLoot("Heart of the Mountains", 0.01),
                new ItemLoot("Ghost King's Crown", 0.02),
                new ItemLoot("Strike Amulet", 0.02),
                new ItemLoot("Raven's Personal Bow", 0.0003),
                new ItemLoot("Poniard of Ghastly Retribution", 0.004),
                new ItemLoot("Odin's Attire", 0.01),
                new ItemLoot("Zol Elixir", 0.01),
                new ItemLoot("Flaming Armor of Magma", 0.05),
                new ItemLoot("Trap of the Vile Spirit", 0.05),
                new ItemLoot("Pirate King's Cutlass", 0.05),
                new ItemLoot("Sor Reactor", 0.001),
                new ItemLoot("Protagonite Chassis", 0.005),
                new ItemLoot("Sor Nucleus", 0.005),
                new ItemLoot("Slime Staff", 0.004),
                new ItemLoot("Cyber Soldier Helm", 0.005),
                new ItemLoot("Enforcer Armor-2000", 0.01),
                new ItemLoot("Necklace of Fallen Grace", 0.01),
                new ItemLoot("Trap of Dark Magic", 0.01),
                new ItemLoot("Hela's Robe", 0.01),
                new ItemLoot("Wand of the Ascended Creation", 0.012),
                new ItemLoot("Gargoyle Stoneplate", 0.01),
                new ItemLoot("Short Circuit", 0.05),
                new ItemLoot("Scepter of Fulmination", 0.05),
                new ItemLoot("Conducting Wand", 0.04),
                new ItemLoot("Robe of the Mad Scientist", 0.05),
                new ItemLoot("Experimental Ring", 0.10),
                new ItemLoot("Mad King's Crook", 0.01),
                new ItemLoot("Aegis of the Citadel", 0.01),
                new ItemLoot("Songstress Attire", 0.01),
                new ItemLoot("Musician's Hat", 0.01),
                new ItemLoot("Venom Cage", 0.01),
                new ItemLoot("Contagion Bracelet", 0.01),
                new ItemLoot("Battleaxe of the Ent", 0.01),
                new ItemLoot("Necklace of Undead Support", 0.01),
                new ItemLoot("Butcher's Plate", 0.0003),
                new ItemLoot("The Eye", 0.004),
                new ItemLoot("Orb of Destiny", 0.004),
                new ItemLoot("Death's Mantle", 0.004),
                new ItemLoot("Righteous Dice", 0.01),
                new ItemLoot("Greeni", 0.01),
                new ItemLoot("Hide of the Feral", 0.01),
                new ItemLoot("Kiskiorab", 0.01),
                new ItemLoot("Deep Blue Anchor", 0.0003),
                new ItemLoot("Master of the House", 0.01),
                new ItemLoot("Water Dragon Silk Robe", 0.05),
                    new ItemLoot("Lucky Slasher", 0.0003),
                    new ItemLoot("Gravachrome", 0.004),
                    new ItemLoot("Mega Blaster", 0.005),
                    new ItemLoot("Soul of Havoc", 0.004),
                    new ItemLoot("Thusala's Slasher", 0.004),
                    new ItemLoot("Queen's Crown", 0.01),
                    new ItemLoot("Garbs of the Frozen Queen", 0.01),
                    new ItemLoot("Treasure of Asgard", 0.05),
                    new ItemLoot("Shield of Ogmur", 0.05),
                    new ItemLoot("Frosty's Walking Stick", 0.05),
                new ItemLoot("Sebafra's Soulcatcher", 0.004),
                new ItemLoot("Cloak of Vampirism", 0.004),
                new ItemLoot("Flame of Misery", 0.004),
                new ItemLoot("Odin's Ravens", 0.01),
                new ItemLoot("Dranbiel Garbs", 0.01),
                new ItemLoot("Undead's Gross Bow", 0.009),
                new ItemLoot("Carrier's Suit", 0.01),
                new ItemLoot("Sincryer's Demise", 0.01),
                new ItemLoot("Soul's Guidance", 0.05),
                new ItemLoot("Plague Poison", 0.05),
                new ItemLoot("Resurrected Warrior's Armor", 0.05),
                new ItemLoot("Etherite Dagger", 0.03),
                new ItemLoot("Ghastly Drape", 0.04),
                new ItemLoot("Mantle of Skuld", 0.04),
                new ItemLoot("Spectral Ring of Horrors", 0.04),
                new ItemLoot("A Yeti's Horn", 0.004),
                new ItemLoot("Yeti Walkers", 0.004),
                new ItemLoot("Thunderfall's Storm", 0.01),
                new ItemLoot("Wand of Pristine Environments", 0.04),
                new ItemLoot("Penetrating Blast Spell", 0.04),
                new ItemLoot("Sandstone Seal", 0.05),
                new ItemLoot("Peppermint Candy Bow", 0.0072),
                new ItemLoot("Festive Quiver", 0.0076),
                new ItemLoot("Elf Suit", 0.0078),
                new ItemLoot("Merrystone", 0.0078),
                new ItemLoot("Star of the North Pole", 0.009),
                new ItemLoot("Wand of Ornaments", 0.009),
                new ItemLoot("North Pole's Slasher", 0.009),
                new ItemLoot("North Pole's Orb", 0.009),
                new ItemLoot("Chocolate Cookie", 0.009),
                new ItemLoot("Robe of Celebration", 0.009),
                new ItemLoot("Santa's Battle Attire", 0.009),
                new ItemLoot("Kurisumasu no Uwagi", 0.009),
                new ItemLoot("Santa's Coat", 0.009),
                new ItemLoot("Santa Hat", 0.009),
                new ItemLoot("Santa's Mitten", 0.009),
                new ItemLoot("Holiday Ring", 0.004),
                new ItemLoot("Ring of the New Sun", 0.001),
                new ItemLoot("Blondie's Claws", 0.0003),
                new ItemLoot("Ceasar's Armor", 0.0003),
                new ItemLoot("Morningstar of Honey", 0.004),
                new ItemLoot("Ring of the Cosmos", 0.004),
                new ItemLoot("Beastly Dice", 0.004),
                new ItemLoot("Bee Wand", 0.01),
                new ItemLoot("Beehemoth Quiver Yellow", 0.025),
                new ItemLoot("Beehemoth Quiver Blue", 0.025),
                new ItemLoot("Beehemoth Quiver Red", 0.025),
                new ItemLoot("Bottle of Condensed Honey", 0.045),
                new ItemLoot("Queen's Stinger Dagger", 0.045),
                new ItemLoot("Axolotl Friend", 0.01),
                new ItemLoot("Anchor of the Chosen", 0.01),
                new ItemLoot("Hivemaster Helm", 0.045),
                new ItemLoot("Nectar Crossfire", 0.05),
                new ItemLoot("Honeytomb Snare", 0.05),
                new ItemLoot("Honey Circlet", 0.05),
                new ItemLoot("Beehemoth Armor Yellow", 0.03),
                new ItemLoot("Beehemoth Armor Blue", 0.03),
                new ItemLoot("Beehemoth Armor Red", 0.03),
                new ItemLoot("Honey Scepter", 0.05),
                new ItemLoot("Orb of Sweet Demise", 0.05),
                new ItemLoot("Wand of the Galaxy", 0.0003),
                new ItemLoot("Crown of the Universe", 0.00028),
                new ItemLoot("Old Farmer's Leather Book", 0.0003),
                new ItemLoot("Page of Catatonia", 0.004),
                new ItemLoot("Rhongomyniad", 0.0038),
                new ItemLoot("March of the Army", 0.01),
                new ItemLoot("Cow Horns", 0.05),
                new ItemLoot("Cow Skin Shield", 0.05),
                new ItemLoot("Milky Orb", 0.05),
                new ItemLoot("Soulfester", 0.0003),
                new ItemLoot("Yukari Sakuragi's Umbrella", 0.0003),
                new ItemLoot("Ghost Robe", 0.004),
                new ItemLoot("Scythe of Death", 0.004),
                new ItemLoot("Gileon's Spirit", 0.004),
                new ItemLoot("Crest of Ruin", 0.003),
                new ItemLoot("Harlequin's Crossbow", 0.01),
                new ItemLoot("Cloak of Bloody Surprises", 0.04),
                new ItemLoot("Handcannon", 0.0003),
                new ItemLoot("Sword of Oryx", 0.004),
                new ItemLoot("Helm of Oryx", 0.004),
                new ItemLoot("Armor of Oryx", 0.004),
                new ItemLoot("Ring of Oryx", 0.004),
                new ItemLoot("Saturn's Orbit", 0.004),
                new ItemLoot("Mask of the Mad God", 0.01),
                new ItemLoot("Vulcanstriker", 0.01),
                new ItemLoot("Rip of Soul", 0.01),
                new ItemLoot("Thousand Shot", 0.05),
                new ItemLoot("Sword of Valor", 0.05),
                new ItemLoot("Sword of the Mad God", 0.03),
                new ItemLoot("Onyx Shield of the Mad God", 0.03),
                new ItemLoot("Almandine Armor of Anger", 0.03),
                new ItemLoot("Almandine Ring of Wrath", 0.03),
                new ItemLoot("Backpack", 0.15),
                new ItemLoot("Boshy Gun", 0.0003),
                new ItemLoot("Harbinger of Fury", 0.004),
                new ItemLoot("Oryx's Decapitator", 0.004),
                new ItemLoot("Seal of Oryx", 0.004),
                new ItemLoot("Vanguard of Oryx", 0.004),
                new ItemLoot("Amulet of Pure Madness", 0.004),
                new ItemLoot("The Twilight Grimoire", 0.004),
                new ItemLoot("Jackpot", 0.01),
                new ItemLoot("Captain America Sword", 0.05),
                new ItemLoot("Band of Oryx", 0.05),
                new ItemLoot("Tsar Bomba", 0.0003),
                new ItemLoot("Titan's Breastplate", 0.004),
                new ItemLoot("Knight's Warhammer", 0.01),
                new ItemLoot("Helm of Duality", 0.01),
                new ItemLoot("Gargoyle Crusher", 0.015),
                new ItemLoot("Cloak of Terradius", 0.01),
                new ItemLoot("Faithless Execution", 0.01),
                new ItemLoot("Ruby Plated Armor", 0.01),
                new ItemLoot("Legendary Stone Sword", 0.01),
                new ItemLoot("Gauntlet of Mortality", 0.01),
                new ItemLoot("Ancient Stone Sword", 0.07),
                new ItemLoot("Ivory Ring", 0.06),
                new ItemLoot("Purity", 0.0003),
                new ItemLoot("Claw of the Beast", 0.004),
                new ItemLoot("General's Greatsword", 0.004),
                new ItemLoot("Kokorowatari", 0.01),
                new ItemLoot("Crystal Trap", 0.01),
                new ItemLoot("Cosmic Cortex", 0.005),
                new ItemLoot("Death's Gem", 0.01),
                new ItemLoot("Rabbit's Foot", 0.01),
                new ItemLoot("Primal Flame", 0.004),
                new ItemLoot("Face of Hades", 0.004),
                new ItemLoot("Lycaon's Hide", 0.004),
                new ItemLoot("Firestorm", 0.005),
                new ItemLoot("Staff of Demonic Power", 0.01),
                new ItemLoot("Hellfire Orb", 0.01),
                new ItemLoot("The Scorched Armor", 0.05),
                new ItemLoot("Prism of Dancing Swords", 0.05),
                new ItemLoot("Staff of the Rising Sun", 0.05),
                new ItemLoot("Ring of the Burning Sun", 0.05),
                new ItemLoot("Clarent", 0.004),
                new ItemLoot("Drakenguard", 0.004),
                new ItemLoot("Bloodlord's Cranium", 0.004),
                new ItemLoot("Lycaon's Heart", 0.004),
                new ItemLoot("Head of the Firebreather", 0.01),
                new ItemLoot("Scorching Scepter", 0.01),
                new ItemLoot("Ring of Solar Focus", 0.01),
                new ItemLoot("Skull of Endless Torment", 0.05),
                new ItemLoot("Fire Dragon Battle Armor", 0.05),
                new ItemLoot("Ultimate Crown", 0.0003),
                new ItemLoot("Staff of Annihilation", 0.0003),
                new ItemLoot("The Forsaken Ring", 0.0045),
                new ItemLoot("Cloak of the King", 0.0048),
                new ItemLoot("Hela's Essence", 0.0045),
                new ItemLoot("King's Crossbow", 0.0095),
                new ItemLoot("King's Visard", 0.01),
                new ItemLoot("Legendary Forgotten Crown", 0.01),
                new ItemLoot("Forgotten Robe", 0.0095),
                new ItemLoot("Grey Belt", 0.01),
                new ItemLoot("Magician's Hide", 0.01),
                new ItemLoot("The Forgotten Crown", 0.04),
                new ItemLoot("Ancient Spell: Pierce", 0.04),
                new ItemLoot("Ultimate Gemstone", 0.0003),
                new ItemLoot("Quasar Piercer", 0.0003),
                new ItemLoot("Greatcloak of Twilight", 0.004),
                new ItemLoot("Wand of Bone", 0.004),
                new ItemLoot("Malevolent Armor", 0.004),
                new ItemLoot("Magic-Infused Dice", 0.004),
                new ItemLoot("Staff of Holy Terror", 0.01),
                new ItemLoot("Hela's Horns", 0.01),
                new ItemLoot("Crown of the Elements", 0.01),
                new ItemLoot("The Twilight Gemstone", 0.04),
                new ItemLoot("Sentient Staff", 0.04),
                new ItemLoot("The Robe of Twilight", 0.04),
                new ItemLoot("Ultimate Bracer", 0.0003),
                new ItemLoot("Defender's Last Stand", 0.0003),
                new ItemLoot("Blades of the Bridge", 0.004),
                new ItemLoot("Bel's Decapitator", 0.004),
                new ItemLoot("Bracer of the Guardian", 0.04),
                new ItemLoot("The Forgotten Ring", 0.04),
                new ItemLoot("Limbsplit Quiver", 0.004),
                new ItemLoot("Snakebound Slasher", 0.005),
                new ItemLoot("Malignant Slasher", 0.009),
                new ItemLoot("Sor Giant Slayer", 0.01),
                new ItemLoot("Medusa's Trap", 0.01),
                new ItemLoot("Cytoplasmic Induced Leather", 0.01),
                new ItemLoot("Samurai's Belt", 0.01),
                new ItemLoot("Sensei's Hat", 0.01),
                new ItemLoot("The Scavenger's Attire", 0.04),
                new ItemLoot("Wand of the Bulwark", 0.05),
                new ItemLoot("Snake Skin Shield", 0.10),
                new ItemLoot("Snake Skin Armor", 0.10),
                new ItemLoot("Snake Eye Ring", 0.10),
                new ItemLoot("Duck Floatie", 0.01),
                new ItemLoot("Robe of Split Worlds", 0.01),
                new ItemLoot("Glazed Edge", 0.01),
                new ItemLoot("Teh Duck Quiver", 0.01),
                new ItemLoot("Duckie Staff", 0.01),
                new ItemLoot("Helm of the Necropolis", 0.004),
                new ItemLoot("Star of Bones", 0.004),
                new ItemLoot("Bloodstone of Enmity", 0.009),
                new ItemLoot("Sky Piercer Wand", 0.01),
                new ItemLoot("The Gilded Blade", 0.01),
                new ItemLoot("Spiritclaw", 0.01),
                new ItemLoot("Sun and Moon Expansion", 0.01),
                new ItemLoot("Loremaker's Staff", 0.01),
                new ItemLoot("Hell's Inferno", 0.01),
                new ItemLoot("Burning Sun Scepter", 0.01),
                new ItemLoot("Drannol's Spirit", 0.01),
                new ItemLoot("Ancient Pendant", 0.01),
                new ItemLoot("Aben's Stoneplate", 0.01),
                new ItemLoot("Platinum Argarius", 0.01),
                new ItemLoot("Anchor of Moses", 0.04),
                new ItemLoot("Ray Katana", 0.04),
                new ItemLoot("Helm of the Juggernaut", 0.04),
                new ItemLoot("Robe of the Summer Solstice", 0.05),
                new ItemLoot("Reaper's Bow", 0.004),
                new ItemLoot("Face of Arachna", 0.01),
                new ItemLoot("Predator Necklace", 0.01),
                new ItemLoot("Sword of the Fallen", 0.04),
                new ItemLoot("Poison Fang Dagger", 0.10),
                new ItemLoot("Spider's Eye Ring", 0.10),
                new ItemLoot("Elicia Blanket", 0.0003),
                new ItemLoot("Blade of the Sprites", 0.004),
                new ItemLoot("Ring of Fleshly Desires", 0.004),
                new ItemLoot("Elemental Obliterator", 0.005),
                new ItemLoot("Dagger of the Endless Void", 0.0011),
                new ItemLoot("Robe of Treasure", 0.01),
                new ItemLoot("Wheel of Flames", 0.01),
                new ItemLoot("Cloak of the Planewalker", 0.04),
                new ItemLoot("Planewalker Armor", 0.04),
                new ItemLoot("Staff of Extreme Prejudice", 0.05),
                new ItemLoot("Cleopatra's Sheath", 0.0003),
                new ItemLoot("Rigormortis", 0.004),
                new ItemLoot("Bonesplinter Robe", 0.004),
                new ItemLoot("A Gruesome Concept", 0.004),
                new ItemLoot("Katana of the Sun", 0.01),
                new ItemLoot("Buckler of the Ancients", 0.01),
                new ItemLoot("Seal of Glowing Honor", 0.01),
                new ItemLoot("Drannol's Judgement", 0.01),
                new ItemLoot("Blade of the Fallen Sky", 0.04),
                new ItemLoot("Ring of the Pyramid", 0.05),
                new ItemLoot("Tome of Holy Protection", 0.05),
                new ItemLoot("Eternal Love", 0.0003),
                new ItemLoot("Blessed Ring of the Tomb", 0.005),
                new ItemLoot("Gungnir", 0.009),
                new ItemLoot("Ring of Immortality", 0.01),
                new ItemLoot("Ancient Longbow", 0.01),
                new ItemLoot("Staff of Royal Revenge", 0.01),
                new ItemLoot("Lightning God Ring", 0.05),
                new ItemLoot("Ring of the Nile", 0.05),
                new ItemLoot("Amulet of the Ancients", 0.01),
                new ItemLoot("Garbs of the Sun God", 0.01),
                new ItemLoot("Gemstone of Divinity", 0.01),
                new ItemLoot("Attire of Chaos", 0.01),
                new ItemLoot("Ring of the Sphinx", 0.05),
                new ItemLoot("Wand of Geb", 0.04),
                new ItemLoot("Book of Geb", 0.04),
                new ItemLoot("Shendyt of Geb", 0.04),
                new ItemLoot("Geb's Ring of Wisdom", 0.04),
                new ItemLoot("Hunter's Chestplate", 0.005),
                new ItemLoot("Hunter's Robe", 0.005),
                new ItemLoot("Hunter's Garbs", 0.005),
                new ItemLoot("Hunter's Suit", 0.005),
                new ItemLoot("Hunter's Hide", 0.005),
                new ItemLoot("Hunter's Armor", 0.005),
                new ItemLoot("Hunter's Amulet", 0.005),
                new ItemLoot("Hunter's Ring", 0.005),
                new ItemLoot("Hunter's Staff", 0.005),
                new ItemLoot("Hunter's Rod", 0.005),
                new ItemLoot("Hunter's Crossbow", 0.005),
                new ItemLoot("Hunter's Bow", 0.005),
                new ItemLoot("Hunter's Wand", 0.005),
                new ItemLoot("Hunter's Cane", 0.005),
                new ItemLoot("Hunter's Dagger", 0.005),
                new ItemLoot("Hunter's Throwing Knife", 0.005),
                new ItemLoot("Hunter's Spear", 0.005),
                new ItemLoot("Hunter's Sword", 0.005),
                new ItemLoot("Hunter's Katana", 0.005),
                new ItemLoot("Hunter's Blade", 0.005),
                new ItemLoot("Boneshatter", 0.004),
                new ItemLoot("Ectoplasm Blade", 0.005),
                new ItemLoot("Soul Buster", 0.01),
                new ItemLoot("Soulkeeper", 0.01),
                new ItemLoot("Mercy of Yazanahar", 0.01),
                new ItemLoot("Shattered War Axe", 0.01),
                new ItemLoot("Spectral Armor", 0.04),
                new ItemLoot("Sheath of the Holy Revival", 0.045),
                new ItemLoot("Ghostly Disguise", 0.05),
                new ItemLoot("Doom Bow", 0.05),
                new ItemLoot("The Necronomicon", 0.05),
                new ItemLoot("Bow of the Morning Star", 0.02),
                new ItemLoot("The Realm Eye", 0.0003),
                new ItemLoot("Dreadcool", 0.001),
                new ItemLoot("Dreadcull", 0.004),
                new ItemLoot("Nightmare Gem", 0.004),
                new ItemLoot("The Apex Bulwark", 0.004),
                new ItemLoot("Unholy Wand", 0.005),
                new ItemLoot("Pernicious Fate-36", 0.01),
                new ItemLoot("Skull of Ravagers", 0.01),
                new ItemLoot("Dirk of Notorious Agents", 0.01),
                new ItemLoot("Zol Wraps", 0.01),
                new ItemLoot("Force Between Avex", 0.01),
                new ItemLoot("Night Dice", 0.04),
                new ItemLoot("Unholy Short Sword", 0.04),
                new ItemLoot("Seal of Blasphemous Prayer", 0.04),
                new ItemLoot("Annoying Firecracker Katana", 0.05),
                new ItemLoot("Plasma Bee Wand", 0.003),
                new ItemLoot("Beacon of Light", 0.003),
                new ItemLoot("Laser Gun", 0.003),
                new ItemLoot("Lightsaber", 0.003),
                new ItemLoot("Star of Light", 0.003),
                new ItemLoot("Lightshow", 0.003),
                new ItemLoot("Skull of the Light Lord", 0.003),
                new ItemLoot("Spaceship's Anchor", 0.003),
                new ItemLoot("Hide of Light", 0.003),
                new ItemLoot("Light Core", 0.003),
                new ItemLoot("Light's Orbit", 0.003),
                new ItemLoot("Plasmastone", 0.003),
                new ItemLoot("Plasma Sprout", 0.003),
                new ItemLoot("Tablet of Doom", 0.004),
                new ItemLoot("The Great Lightsword", 0.0095),
                new ItemLoot("V-L Spark Armor", 0.01),
                new ItemLoot("Starcrash Ring", 0.01),
                new ItemLoot("Snare of the Lurking Titan", 0.0003),
                new ItemLoot("Mari's Spirit", 0.0003),
                new ItemLoot("Omnipotence Ring", 0.004),
                new ItemLoot("Sword of the Colossus", 0.01),
                new ItemLoot("Marble Seal", 0.01),
                new ItemLoot("Breastplate of New Life", 0.01),
                new ItemLoot("Magical Lodestone", 0.01),
                new ItemLoot("Bow of the Void", 0.01),
                new ItemLoot("Quiver of the Shadows", 0.01),
                new ItemLoot("Armor of Nil", 0.01),
                new ItemLoot("Sourcestone", 0.01),
                new ItemLoot("Staff of Unholy Sacrifice", 0.01),
                new ItemLoot("Skull of Corrupted Souls", 0.01),
                new ItemLoot("Ritual Robe", 0.01),
                new ItemLoot("Bloodshed Ring", 0.01),
                new ItemLoot("Arcanuo's Zol Lance", 0.0025),
                new ItemLoot("Garments of Goblin Monarch", 0.01),
                new ItemLoot("Forest Parry Technique", 0.01),
                new ItemLoot("Petrified Lophop", 0.01),
                new ItemLoot("Unholy Spell", 0.04),
                new ItemLoot("Core of Corruption", 0.01),
                new ItemLoot("Oath of Cinder", 0.01),
                new ItemLoot("Bubble Discharger Staff", 0.01),
                new ItemLoot("Robes of Aldragine", 0.01),
                new ItemLoot("Midnight Star", 0.05),
                new ItemLoot("Void Blade", 0.05),
                new ItemLoot("pD Armor", 0.05),
                new ItemLoot("Atonement", 0.004),
                new ItemLoot("Blazing Machete", 0.004),
                new ItemLoot("Flaming Horizons Anchor", 0.004),
                new ItemLoot("Nightmare Gem Gem's Gem", 0.004),
                new ItemLoot("Elytra", 0.004),
                new ItemLoot("Mask of Thunders", 0.0003),
                new ItemLoot("Dice of the Royals", 0.0003),
                new ItemLoot("Paladin's Waraxe", 0.004),
                new ItemLoot("Necrotic Boneplate", 0.004),
                new ItemLoot("The Flamarang", 0.005),
                new ItemLoot("Crown of War", 0.0098),
                new ItemLoot("Devil Dice", 0.01),
                new ItemLoot("Demon Summoning Tome", 0.01),
                new ItemLoot("The Infernus", 0.01),
                new ItemLoot("Orb of Conflict", 0.05),
                new ItemLoot("Hell's Breastplate", 0.04),
                new ItemLoot("Flaming Boomerang", 0.05),
                new ItemLoot("Z Saber", 0.0003),
                new ItemLoot("Larry Gun", 0.004),
                new ItemLoot("Executioner's Guillotine", 0.004),
                new ItemLoot("Dreadstump's Lost Anchor", 0.04),
                new ItemLoot("Coral Anchor", 0.04),
                new ItemLoot("Heart of Boshy", 0.01),
                new ItemLoot("An Astonishing Happening", 0.01),
                new ItemLoot("Poseidon's Gauntlet", 0.004),
                new ItemLoot("Amulet of Oryx", 0.004),
                new ItemLoot("Shadow Suit", 0.01),
                new ItemLoot("The Rainstorm", 0.01),
                new ItemLoot("Elemental Pendant", 0.01),
                new ItemLoot("Pretty Flower Amulet", 0.01),
                new ItemLoot("Pretty Flower Wand", 0.01),
                new ItemLoot("Helm of Erebus", 0.01),
                new ItemLoot("Octopussy", 0.01),
                new ItemLoot("Helm of the Juggernaut", 0.05),
                new ItemLoot("Flesh Trap", 0.004),
                new ItemLoot("Helldom Shell", 0.004),
                new ItemLoot("Demon Lord's Wrath", 0.005),
                new ItemLoot("Blade of the Underworld", 0.01),
                new ItemLoot("Shattered Caliburn", 0.01),
                new ItemLoot("Robe of Bloodbath", 0.01),
                new ItemLoot("Abaddon's Bracelet", 0.01),
                new ItemLoot("Hellstone", 0.01),
                new ItemLoot("Burning Tome", 0.01),
                new ItemLoot("Book of Flames", 0.035),
                new ItemLoot("Destructor Armor", 0.05),
                new ItemLoot("Melting Ring", 0.05),
                new ItemLoot("Phoenix Ashes", 0.05),
                new ItemLoot("Ring of the Demon Lord", 0.05),
                new ItemLoot("Demon Blade", 0.05),
                new ItemLoot("Sword of Illumination", 0.02),
                new ItemLoot("Thousand Suns Spell", 0.05),
                new ItemLoot("Cursed Wand of the Corrupted", 0.004),
                new ItemLoot("Favor of Fortune", 0.004),
                new ItemLoot("Necklace of Fangs", 0.004),
                new ItemLoot("Oathsworn's Staff", 0.008),
                new ItemLoot("Oathsworn's Garments", 0.008),
                new ItemLoot("The Forgotten Conduit", 0.009),
                new ItemLoot("Cremation", 0.01),
                new ItemLoot("The Executioner", 0.01),
                new ItemLoot("Sons Sparkling", 0.04),
                new ItemLoot("Tablet of the King's Avatar", 0.05),
                new ItemLoot("Pizza Ring", 0.05),
                new ItemLoot("Ji Robe", 0.0003),
                new ItemLoot("Garugen", 0.004),
                new ItemLoot("Candy Crusher", 0.05),
                new ItemLoot("Candy-Coated Armor", 0.05),
                new ItemLoot("Pixie-Enchanted Sword", 0.02),
                new ItemLoot("Seal of the Enchanted Forest", 0.03),
                new ItemLoot("Fairy Plate", 0.03),
                new ItemLoot("Ring of Pure Wishes", 0.03),
                new ItemLoot("Candy Ring", 0.1),
                new ItemLoot("Bonemail of the Fallen", 0.004),
                new ItemLoot("Candy-Coated Armor", 0.05),
                new ItemLoot("Pixie-Enchanted Sword", 0.02),
                new ItemLoot("Seal of the Enchanted Forest", 0.03),
                new ItemLoot("Fairy Plate", 0.03),
                new ItemLoot("Ring of Pure Wishes", 0.03),
                new ItemLoot("Candy Ring", 0.1),
                new ItemLoot("Harbinger", 0.004),
                new ItemLoot("Insurgency Amulet", 0.01),
                new ItemLoot("Candy-Coated Armor", 0.05),
                new ItemLoot("Pixie-Enchanted Sword", 0.02),
                new ItemLoot("Seal of the Enchanted Forest", 0.03),
                new ItemLoot("Fairy Plate", 0.03),
                new ItemLoot("Ring of Pure Wishes", 0.03),
                new ItemLoot("Candy Ring", 0.1),
                new ItemLoot("Super Mushroom", 0.04),
                new ItemLoot("Harlequin Armor", 0.05),
                new ItemLoot("Candy Ring", 0.15),
                new ItemLoot("Karen Jacket", 0.0003),
                new ItemLoot("Essence of Death", 0.004),
                new ItemLoot("Phantom Cleaver", 0.004),
                new ItemLoot("Tome of Fleshly Desires", 0.004),
                new ItemLoot("Sanic Head", 0.005),
                new ItemLoot("Kid's Cape", 0.005),
                new ItemLoot("Treasure of the Universe", 0.0095),
                new ItemLoot("Blade of the Titan", 0.01),
                new ItemLoot("The Gravedigger's Disguise", 0.01),
                new ItemLoot("Merit of Rebellion", 0.05),
                new ItemLoot("Ring of the Cubes", 0.05),
                new ItemLoot("Dirk of Cronus", 0.05),
                new ItemLoot("Amulet of Ascension", 0.0003),
                new ItemLoot("Unstable Jewel", 0.004),
                new ItemLoot("Frozen Time", 0.005),
                new ItemLoot("Gem Sword", 0.01),
                new ItemLoot("Scorching Refraction", 0.01),
                new ItemLoot("Enchanted Uru Sword", 0.0095),
                new ItemLoot("Winds of Change", 0.01),
                new ItemLoot("Gemstone Attire", 0.01),
                new ItemLoot("Robe of Majesty", 0.01),
                new ItemLoot("Purification Crystal", 0.01),
                new ItemLoot("Forgotten Zol Gem", 0.01),
                new ItemLoot("MC Irons Shield", 0.04),
                new ItemLoot("Crystal Sword", 0.05),
                new ItemLoot("Crystal Wand", 0.05),
                new ItemLoot("Wall of Gore", 0.004),
                new ItemLoot("Vest of Doomed Souls", 0.004),
                new ItemLoot("Shadowsteel Plate", 0.005),
                new ItemLoot("Throwing Spear", 0.01),
                new ItemLoot("Colossal Skull", 0.01),
                new ItemLoot("Crown of the Ice", 0.01),
                new ItemLoot("Bracelet of the Demolished", 0.01),
                new ItemLoot("Final Hour", 0.05),
                new ItemLoot("Tome of Purification", 0.05),
                new ItemLoot("St. Abraham's Wand", 0.08),
                new ItemLoot("Bone Dagger", 0.08),
                new ItemLoot("Chasuble of Holy Light", 0.1),
                new ItemLoot("Ring of Divine Faith", 0.1),
                new ItemLoot("Whisper of the Seven Seas", 0.0003),
                new ItemLoot("Soul Warden", 0.004),
                new ItemLoot("Seal of the Necropolis", 0.004),
                new ItemLoot("The Nuruaj", 0.01),
                new ItemLoot("The Darkin Skull", 0.01),
                new ItemLoot("Shiny Diver's Breastplate", 0.01),
                new ItemLoot("Entropy Reactor", 0.04),
                new ItemLoot("Orb of Aether", 0.045),
                new ItemLoot("Spirit Dagger", 0.05),
                new ItemLoot("Ghostly Prism", 0.05),
                new ItemLoot("Spectral Cloth Armor", 0.08),
                new ItemLoot("Captain's Ring", 0.10),
                new ItemLoot("Breastplate of the Plague", 0.0003),
                new ItemLoot("Skull of Vampirism", 0.004),
                new ItemLoot("Reinforced Ribcage", 0.004),
                new ItemLoot("The Gravedigger's Shovel", 0.009),
                new ItemLoot("Dagger of Tindailius", 0.01),
                new ItemLoot("Ring of Ortar", 0.05),
                new ItemLoot("Staff of Nature", 0.01),
                new ItemLoot("The Soul Ring", 0.01),
                new ItemLoot("Oblivion", 0.004),
                new ItemLoot("Scepter of the Ancients", 0.004),
                new ItemLoot("Amulet of the Underworld", 0.01),
                new ItemLoot("Waraxe of Judgement", 0.01),
                new ItemLoot("The Crimson Anchor", 0.01),
                new ItemLoot("Book of Flames", 0.04),
                new ItemLoot("Star Ring", 0.01),
                new ItemLoot("Leaf Dragon Hide Armor", 0.05),
                new ItemLoot("Sewer Cocktail", 0.05),
                new ItemLoot("The Oddishclaw", 0.0003),
                new ItemLoot("Vinelocker", 0.004),
                new ItemLoot("Twisted Earth Dice", 0.01),
                new ItemLoot("The Eternal Kinstone", 0.004),
                new ItemLoot("Overgrown Skull", 0.01),
                new ItemLoot("Petrified Dragonroot", 0.01),
                new ItemLoot("The Soul Collector", 0.01),
                new ItemLoot("Speedier Sprout", 0.01),
                new ItemLoot("Gravachrome Grass", 0.004),
                new ItemLoot("Elimination", 0.01),
                new ItemLoot("Butterfly Dagger", 0.01),
                new ItemLoot("Katana of Mythical Alliance", 0.01),
                new ItemLoot("Opus Salutem", 0.01),
                new ItemLoot("Bow of the Ugajuajn", 0.01),
                new ItemLoot("The Odyssey", 0.01),
                new ItemLoot("Ring of the Unstable Mind", 0.01),
                new ItemLoot("Burning Wood Mask", 0.05),
                new ItemLoot("Wing Necklace", 0.05),
                new ItemLoot("Leaf Bow", 0.05),
                new ItemLoot("Doku No Ken", 0.05),
                new ItemLoot("Poseidon's Trident", 0.0003),
                new ItemLoot("Wavebreaker", 0.005),
                new ItemLoot("Robe of the Draconic Overlord", 0.005),
                new ItemLoot("Bow of Warped Coral", 0.01),
                new ItemLoot("Flames of Purity", 0.01),
                new ItemLoot("Covering of Mermaid Goddess", 0.01),
                new ItemLoot("Radiant Wand of Royalism", 0.01),
                new ItemLoot("Oceanic Treasure", 0.04),
                new ItemLoot("Coral Bow", 0.05),
                new ItemLoot("Coral Venom Trap", 0.05),
                new ItemLoot("Coral Silk Armor", 0.08),
                new ItemLoot("Coral Ring", 0.12)
                )
            )
            ;
    }
}